### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by satnam6502** [fabric8io/fluent-plugin-kubernetes_metadata_filter#1]
Probably entirely my fault, but I can't seem to install this plug-in.
```
$ sudo gem install fluent-plugin-kubernetes_metadata_filter
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-kubernetes_metadata_filter:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/msgpack-0.5.11 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/msgpack-0.5.11/ext/msgpack/gem_make.out
```

**Comment by jimmidyson** [comment]
As discussed in email, you need to install ruby-dev or ruby-devel to be able to build & install.
