### ISSUE TITLE
kube-apiserver high cpu usage

### ISSUE THREAD

**Issue by vissible** [fabric8io/fluent-plugin-kubernetes_metadata_filter#102]
kubernetes: 1.8.4 
fluentd: 0.12.41
fluent-plugin-systemd: v0.0.9
fluent-plugin-kubernetes_metadata_filter: v1.0.0

The fluent-plugin-kubernetes_metadata_filter caused kube-apiserver very high cpu usage.

```
# docker logs -f --tail=10 9dc7e8de5231 |grep -v dump
2017-12-08 05:03:45 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 21, namespace_cache_api_updates: 10533, pod_cache_api_updates: 10498, id_cache_miss: 10533, pod_cache_api_nil_error: 72, pod_cac
he_miss: 37, pod_cache_watch_misses: 4
2017-12-08 05:04:15 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 21, namespace_cache_api_updates: 11926, pod_cache_api_updates: 11888, id_cache_miss: 11926, pod_cache_api_nil_error: 78, pod_cac
he_miss: 40, pod_cache_watch_misses: 4
2017-12-08 05:04:45 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 22, namespace_cache_api_updates: 13004, pod_cache_api_updates: 12959, id_cache_miss: 13004, pod_cache_api_nil_error: 93, pod_cac
he_miss: 48, pod_cache_watch_misses: 4
2017-12-08 05:05:15 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 22, namespace_cache_api_updates: 14409, pod_cache_api_updates: 14361, id_cache_miss: 14409, pod_cache_api_nil_error: 99, pod_cac
he_miss: 51, pod_cache_watch_misses: 4
2017-12-08 05:05:45 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 22, namespace_cache_api_updates: 15794, pod_cache_api_updates: 15740, id_cache_miss: 15794, pod_cache_api_nil_error: 111, pod_ca
che_miss: 57, pod_cache_watch_misses: 4
2017-12-08 05:06:15 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 22, namespace_cache_api_updates: 17167, pod_cache_api_updates: 17111, id_cache_miss: 17167, pod_cache_api_nil_error: 115, pod_ca
che_miss: 59, pod_cache_watch_misses: 4
2017-12-08 05:06:45 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 22, namespace_cache_api_updates: 18588, pod_cache_api_updates: 18528, id_cache_miss: 18588, pod_cache_api_nil_error: 123, pod_ca
che_miss: 63, pod_cache_watch_misses: 4
2017-12-08 05:07:15 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 22, namespace_cache_api_updates: 19688, pod_cache_api_updates: 19627, id_cache_miss: 19689, pod_cache_api_nil_error: 127, pod_ca
che_miss: 65, pod_cache_orphaned_record: 1, namespace_cache_api_nil_error: 1, pod_cache_watch_misses: 4
2017-12-08 05:07:45 +0000 [info]: stats - namespace_cache_size: 6, pod_cache_size: 22, namespace_cache_api_updates: 21142, pod_cache_api_updates: 21077, id_cache_miss: 21143, pod_cache_api_nil_error: 135, pod_ca
che_miss: 69, pod_cache_orphaned_record: 1, namespace_cache_api_nil_error: 1, pod_cache_watch_misses: 4
```

**Comment by jcantrill** [comment]
@vissible Are you able to verify if the cpu usage is different with the latest v0.33.0 version of the plugin.  The default cache size is 1000 and you have over that amount in updates which should cause it to roll off entries.  I presume you additionally have 'watch' enabled?

**Comment by vissible** [comment]
The cpu usage of v0.33.0 is normal.
Is 'watch' is defualt: false for v0.33.0?
Here is my configuration,
```
    <filter kubernetes.**>
      type kubernetes_metadata
      use_journal true
    </filter>
```

**Comment by jcantrill** [comment]
@vissible We are making some additional modifications with https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/103  Could you please pull and build that gem and see if you have differences to what is published with the 1.0.0 version?

**Comment by vissible** [comment]
updates reduced, but got transaction failed errors.

```
2017-12-12 10:39:09 +0000 [warn]: emit transaction failed: error_class=NameError error="undefined local variable or method `metdata' for #<Fluent::KubernetesMetadataFilter:0x007fc5f4cd99e0>\nDid you mean?  metadata" location="/var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-1.0.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:307:in `get_pod_metadata'" tag="kubernetes.journal.container"
  2017-12-12 10:39:09 +0000 [warn]: suppressed same stacktrace
2017-12-12 10:39:09 +0000 [warn]: emit transaction failed: error_class=NameError error="undefined local variable or method `metdata' for #<Fluent::KubernetesMetadataFilter:0x007fc5f4cd99e0>\nDid you mean?  metadata" location="/var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-1.0.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:307:in `get_pod_metadata'" tag="journal"
  2017-12-12 10:39:09 +0000 [warn]: suppressed same stacktrace
2017-12-12 10:39:09 +0000 [error]: Exception emitting record: undefined local variable or method `metdata' for #<Fluent::KubernetesMetadataFilter:0x007fc5f4cd99e0>
Did you mean?  metadata
2017-12-12 10:39:09 +0000 [warn]: emit transaction failed: error_class=NameError error="undefined local variable or method `metdata' for #<Fluent::KubernetesMetadataFilter:0x007fc5f4cd99e0>\nDid you mean?  metadata" location="/var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-1.0.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:307:in `get_pod_metadata'" tag="kubernetes.journal.container"
  2017-12-12 10:39:09 +0000 [warn]: suppressed same stacktrace
2017-12-12 10:39:09 +0000 [warn]: emit transaction failed: error_class=NameError error="undefined local variable or method `metdata' for #<Fluent::KubernetesMetadataFilter:0x007fc5f4cd99e0>\nDid you mean?  metadata" location="/var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-1.0.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:307:in `get_pod_metadata'" tag="journal"
  2017-12-12 10:39:09 +0000 [warn]: suppressed same stacktrace
2017-12-12 10:39:09 +0000 [error]: Exception emitting record: undefined local variable or method `metdata' for #<Fluent::KubernetesMetadataFilter:0x007fc5f4cd99e0>
Did you mean?  metadata
2017-12-12 10:39:38 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 4, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, namespace_cache_api_updates: 20, pod_cache_api_updates: 4, id_cache_miss: 20, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
2017-12-12 10:40:08 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 5, namespace_cache_api_updates: 21, pod_cache_api_updates: 5, id_cache_miss: 21, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
2017-12-12 10:40:38 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 5, merge_json_parse_errors: 1, namespace_cache_api_updates: 21, pod_cache_api_updates: 5, id_cache_miss: 21, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
2017-12-12 10:41:08 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 5, merge_json_parse_errors: 2, namespace_cache_api_updates: 21, pod_cache_api_updates: 5, id_cache_miss: 21, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
2017-12-12 10:41:38 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 5, merge_json_parse_errors: 2, namespace_cache_api_updates: 21, pod_cache_api_updates: 5, id_cache_miss: 21, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
2017-12-12 10:42:08 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 9, merge_json_parse_errors: 3, namespace_cache_api_updates: 25, pod_cache_api_updates: 9, id_cache_miss: 25, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
2017-12-12 10:42:39 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 11, namespace_cache_api_updates: 27, pod_cache_api_updates: 11, id_cache_miss: 27, merge_json_parse_errors: 3, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
2017-12-12 10:43:10 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 11, merge_json_parse_errors: 4, namespace_cache_api_updates: 27, pod_cache_api_updates: 11, id_cache_miss: 27, pod_cache_watch_misses: 13, pod_cache_watch_ignored: 2, pod_cache_watch_delete_ignored: 2, pod_cache_watch_updates: 1, id_cache_pod_not_found_namespace: 16, pod_cache_api_nil_error: 16
```

**Comment by jcantrill** [comment]
Yes... obvious lack of unit tests that will be forthcoming to fix this error.  Thank you for providing some testing

**Comment by jcantrill** [comment]
@vissible updated the PR to address the undefined variable but not CPU.  CPU is related to continually trying to fetch metadata for records where the API server will never return meta (e.g. deleted pod for which we never processed any records, temp. network issue to api server)

**Comment by jcantrill** [comment]
@vissible could I ask you to run your usecase again?  One of the issues I believe we see is we were continually checking the api server even when processing records from delete pods and namespaces.  I'm not certain if that was the case you see.
