### ISSUE TITLE
error_class=NoMethodError error="undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by micdah** [fabric8io/fluent-plugin-kubernetes_metadata_filter#134]
I am seeing a lot of exceptions from the kubernetes metadata filter, and I am unsure what is wrong.

Here is an example log dump:
```
2018-05-16 10:41:53 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `[]' for nil:NilClass" location="/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.0.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:308:in `filter_stream_from_files'" tag="kubernetes.var.log.containers.noteservice-eventhandler-6fbd89b566-ffmds_default_noteservice-eventhandler-014619db36e8d31dd454ea7d76f24e76c65bb56811cd61629321af59b9bd0b41.log"
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.0.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:308:in `filter_stream_from_files'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:177:in `block in filter_stream'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:177:in `each'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:177:in `reduce'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:177:in `filter_stream'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:158:in `emit_events'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:96:in `emit_stream'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/out_relabel.rb:29:in `process'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:762:in `emit_sync'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:159:in `emit_events'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/event_router.rb:96:in `emit_stream'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:385:in `receive_lines'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:503:in `wrap_receive_lines'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:714:in `block in handle_notify'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:758:in `with_io'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:692:in `handle_notify'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:688:in `block in on_notify'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:688:in `synchronize'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:688:in `on_notify'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:534:in `on_notify'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:507:in `attach'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:264:in `setup_watcher'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:292:in `block in start_watchers'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:278:in `each'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:278:in `start_watchers'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:258:in `refresh_watchers'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/in_tail.rb:193:in `start'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:165:in `block in start'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:153:in `each'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:153:in `block in lifecycle'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:140:in `each'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:140:in `lifecycle'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/root_agent.rb:164:in `start'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/engine.rb:274:in `start'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/engine.rb:219:in `run'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:774:in `run_engine'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:523:in `block in run_worker'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:699:in `main_process'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/supervisor.rb:518:in `run_worker'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2018-05-16 10:41:53 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-05-16 10:41:53 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/bin/fluentd:8:in `<top (required)>'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd:22:in `load'
  2018-05-16 10:41:53 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd:22:in `<main>'
```

**Comment by richm** [comment]
looks like we need to cherrypick https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/9b05ff18cfd648e84c1c689375b9bd6effe1e015#diff-83453022bdb83378e6c454e99caacd36 to master
