### ISSUE TITLE
Kept getting "failed to flush buffer....too many connection resets"

### ISSUE THREAD

**Issue by beth2016** [fabric8io/fluent-plugin-kubernetes_metadata_filter#176]
Hi all,
I see a bunch of these messages.   Anyone know how to get rid of them?  Thanks.   

```
2019-05-21 14:03:48 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-05-21 14:03:49 +0000 chunk="589664d6de9230d19aca58b6039e2e88" error_class=Net::HTTP::Persistent::Error error="too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 requests on 69868501914120, last used 1558447428.009135 seconds ago"
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/protocol.rb:181:in `rbuf_fill'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/http/response.rb:40:in `read_status_line'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/http/response.rb:29:in `read_new'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:1494:in `block in transport_request'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:1491:in `catch'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:1491:in `transport_request'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:1464:in `request'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:951:in `block in request'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:648:in `connection_for'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/net-http-persistent-3.0.1/lib/net/http/persistent.rb:945:in `request'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-splunk-hec-1.0.1/lib/fluent/plugin/out_splunk_hec.rb:331:in `send_to_hec'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-splunk-hec-1.0.1/lib/fluent/plugin/out_splunk_hec.rb:155:in `write'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:1099:in `try_flush'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:1378:in `flush_thread_run'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin/output.rb:440:in `block (2 levels) in start'
  2019-05-21 14:03:48 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by richm** [comment]
I don't know, but it does not appear to have anything to do with this plugin
