### ISSUE TITLE
two "rake tests" are failing...both because the "labels" key/value pair has "labels" prefixed with ":"

### ISSUE THREAD

**Issue by stensonb** [fabric8io/fluent-plugin-kubernetes_metadata_filter#18]
```bash
/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_filter_kubernetes_metadata.rb:307:in `block (2 levels) in <class:KubernetesMetadataFilterTest>'
<{:docker=>
  {:container_id=>
    "49095a2894da899d3b327c5fde1e056a81376cc9a8f8b09a195f2a92bceed459"},
 :kubernetes=>
  {:container_name=>"fabric8-console-container",
   :host=>"jimmi-redhat.localnet",
   :labels=>{"kubernetes_io/test"=>"somevalue"},
   :namespace_name=>"default",
   :pod_id=>"c76927af-f563-11e4-b32d-54ee7527188d",
   :pod_name=>"fabric8-console-controller-98rqc"}}> expected but was
<{:docker=>
  {:container_id=>
    "49095a2894da899d3b327c5fde1e056a81376cc9a8f8b09a195f2a92bceed459"},
 :kubernetes=>
  {:container_name=>"fabric8-console-container",
   :host=>"jimmi-redhat.localnet",
   :labels=>{:"kubernetes_io/test"=>"somevalue"},
   :namespace_name=>"default",
   :pod_id=>"c76927af-f563-11e4-b32d-54ee7527188d",
   :pod_name=>"fabric8-console-controller-98rqc"}}>

diff:
  {:docker=>
    {:container_id=>
      "49095a2894da899d3b327c5fde1e056a81376cc9a8f8b09a195f2a92bceed459"},
   :kubernetes=>
    {:container_name=>"fabric8-console-container",
     :host=>"jimmi-redhat.localnet",
?    :labels=>{:"kubernetes_io/test"=>"somevalue"},
     :namespace_name=>"default",
     :pod_id=>"c76927af-f563-11e4-b32d-54ee7527188d",
     :pod_name=>"fabric8-console-controller-98rqc"}}
```

the above output is from <code>rake test</code> and is showing a diff of the desired vs. expected output...the "labels" key/value pair is incorrect, as the "kubernetes_io/test" key is prefixed with a colon ":"

**Comment by stensonb** [comment]
this is failing because the </code>.ruby-version</code> specifies "2.0.0":

```bash
Bryans-MacBook-Pro-2:git bryan$ cd fluent-plugin-kubernetes_metadata_filter/
✔ ~/git/fluent-plugin-kubernetes_metadata_filter [master|✚ 2…1] 
13:33 $ cat .ruby-version 
2.0.0✔ ~/git/fluent-plugin-kubernetes_metadata_filter [master|✚ 2…1] 
13:33 $ rvm list

rvm rubies

   ruby-1.9.3-p551 [ x86_64 ]
=> ruby-2.0.0-p643 [ x86_64 ]
   ruby-2.1.3 [ x86_64 ]
   ruby-2.2.0 [ x86_64 ]
 * ruby-2.2.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

✔ ~/git/fluent-plugin-kubernetes_metadata_filter [master|✚ 2…1] 
13:33 $ bundle exec rake test
/Users/bryan/.rvm/rubies/ruby-2.0.0-p643/bin/ruby -W -w -I"lib:test" -I"/Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib" "/Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib/rake/rake_test_loader.rb" "test/plugin/test_filter_kubernetes_metadata.rb" 
/Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:15:in `require': /Users/bryan/git/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_filter_kubernetes_metadata.rb:320: syntax error, unexpected ':', expecting => (SyntaxError)
              'kubernetes_io/test': 'somevalue'
                                   ^
/Users/bryan/git/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_filter_kubernetes_metadata.rb:321: syntax error, unexpected '}', expecting keyword_end
/Users/bryan/git/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_filter_kubernetes_metadata.rb:349: syntax error, unexpected ':', expecting =>
              'kubernetes.io/test': 'somevalue'
                                   ^
/Users/bryan/git/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_filter_kubernetes_metadata.rb:350: syntax error, unexpected '}', expecting keyword_end
	from /Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -W -w -I"lib:test" -I"/Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib" "/Users/bryan/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.1.1/lib/rake/rake_test_loader.rb" "test/plugin/test_filter_kubernetes_metadata.rb" ]
/Users/bryan/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/Users/bryan/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test => base_test
(See full trace by running task with --trace)
```

I noticed Circle is using 2.2.0, so I tried it, and it works.  So, this issue is fixed by updating the <code>.ruby-version</code> file to "2.2.0"...PR is forthcoming

**Comment by stensonb** [comment]
PR #19 contains the update to point to the ruby 2.2.0
