### ISSUE TITLE
2.4.0: Emit Transaction Failure

### ISSUE THREAD

**Issue by david-rooke** [fabric8io/fluent-plugin-kubernetes_metadata_filter#196]
Fluentd Version: 1.7.1
Plugin Version: 2.4.0

Am seeing the following error in the log:
```
{"time":"2019-10-25 08:41:29.685","level":"warn","message":"emit transaction failed: error_class=NoMethodError error=\"undefined method `chop' for {}:Hash\" location=\"/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:311:in `create_time_from_record'\" tag=\"kubernetes.var.log.containers.app-1-7c78995b84-b4ngz_app-d7cfa6b97889ff7d146ea8597b8b8447d863328aa27972177d67de4777ba5318.log\"","worker_id":0}
{"time":"2019-10-25 08:41:29.686","level":"warn","worker_id":0,"message":"/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:311:in `create_time_from_record'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:331:in `block in filter_stream'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event.rb:197:in `block in each'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event.rb:196:in `each'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event.rb:196:in `each'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:328:in `filter_stream'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event_router.rb:178:in `block in filter_stream'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event_router.rb:178:in `each'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event_router.rb:178:in `reduce'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event_router.rb:178:in `filter_stream'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event_router.rb:159:in `emit_events'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/event_router.rb:97:in `emit_stream'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:410:in `receive_lines'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:528:in `wrap_receive_lines'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:762:in `block in handle_notify'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:806:in `with_io'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:742:in `handle_notify'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:738:in `block in on_notify'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:738:in `synchronize'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:738:in `on_notify'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:558:in `on_notify'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:532:in `attach'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:281:in `setup_watcher'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:312:in `block in start_watchers'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:298:in `each'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:298:in `start_watchers'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:275:in `refresh_watchers'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/plugin/in_tail.rb:203:in `start'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:203:in `block in start'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `each'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:191:in `block in lifecycle'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `each'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:178:in `lifecycle'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/root_agent.rb:202:in `start'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:274:in `start'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/engine.rb:219:in `run'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:808:in `run_engine'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:551:in `block in run_worker'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:733:in `main_process'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/supervisor.rb:546:in `run_worker'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/lib/fluent/command/fluentd.rb:320:in `<top (required)>'\n/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.1/bin/fluentd:8:in `<top (required)>'\n/fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'\n/fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'"}
```

This blocking transmission for some log sources. How do you suggest we deal with this?

**Comment by jcantrill** [comment]
This is likely because the plugin is unable to determine a valid  time for the record as the error is here:
```
    def create_time_from_record(record, internal_time)
      time_key = @time_fields.detect{ |ii| record.has_key?(ii) }
      time = record[time_key]
      if time.nil? || time.chop.empty?
        # `internal_time` is a Fluent::EventTime, it can't compare with Time.
        return Time.at(internal_time.to_f)
      end
```
The exceptable fields:
```
      @time_fields = []
      @time_fields.push('_SOURCE_REALTIME_TIMESTAMP', '__REALTIME_TIMESTAMP') if @use_journal || @use_journal.nil?
      @time_fields.push('time') unless @use_journal
      @time_fields.push('@timestamp') if @lookup_from_k8s_field
```
I'm assuming `record` is created to return an empty hash (the default) upon a missed key.  Without a patch to the code which would be a check to respond to `chop`, consider looking at your records to see if your logs have a time stamp

**Comment by beth2016** [comment]
I am seeing the same issue as well.

**Comment by toan-hf** [comment]
I am seeing the same issue as well with v2.3.0 
```2019-12-19 14:23:15 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `unstaged?' for nil:NilClass" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/plugin/buffer.rb:339:in `block (2 levels) in write'" tag="kubernetes.name.of.pod-93c13ae7644f56afeadf4f7c7826a49a0d6cec737d245587799c6b4dc33de490.log"```

**Comment by jcantrill** [comment]
> I am seeing the same issue as well with v2.3.0
> 
> ```
> 2019-12-19 14:23:15 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `unstaged?' for nil:NilClass" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.4/lib/fluent/plugin/buffer.rb:339:in `block (2 levels) in write'" tag="kubernetes.name.of.pod-93c13ae7644f56afeadf4f7c7826a49a0d6cec737d245587799c6b4dc33de490.log"
> ```

This error is unlikely to be related to this plugin as it implements no buffering code `/lib/fluent/plugin/buffer.rb` Please investigate your output plugin

**Comment by toan-hf** [comment]
@jcantrill my current configuration for output has buffer implemented. 
`
 <match **>
      @type copy
      <store>
        @type gelf
        @id out_graylog
        @log_level warn
        include_tag_key true
        host "#{ENV['FLUENT_GRAYLOG_HOST']}"
        port "#{ENV['FLUENT_GRAYLOG_PORT']}"
        protocol udp
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode immediate
          retry_type exponential_backoff
          flush_thread_count 800
          flush_thread_interval 2
          retry_forever
          retry_max_interval 30
          chunk_limit_size "9M"
          queue_limit_length "800"
          overflow_action drop_oldest_chunk
          total_limit_size 8192MB
        </buffer>
      </store>
      <store>
        @type prometheus
        <metric>
          name fluentd_aggregator_output_status_num_records_total
          type counter
          desc The total number of outgoing records
          <labels>
            app $.kubernetes.labels.app
            ns $.kubernetes.namespace_name
          </labels>
        </metric>
      </store>
    </match>
`

**Comment by jcantrill** [comment]
Closing not issue with this plugin. Note the following grep of fluent code: 
```
fluentd]$ grep -r unstaged lib
lib/fluent/plugin/buffer.rb:        unstaged_chunks = {} # metadata => [chunk, chunk, ...]
lib/fluent/plugin/buffer.rb:              elsif chunk.unstaged?
lib/fluent/plugin/buffer.rb:                unstaged_chunks[metadata] ||= []
lib/fluent/plugin/buffer.rb:                unstaged_chunks[metadata] << chunk
lib/fluent/plugin/buffer.rb:            if enqueue || first_chunk.unstaged? || chunk_size_full?(first_chunk)
lib/fluent/plugin/buffer.rb:              if enqueue || chunk.unstaged? || chunk_size_full?(chunk)
lib/fluent/plugin/buffer.rb:                if unstaged_chunks[m]
lib/fluent/plugin/buffer.rb:                  u = unstaged_chunks[m].pop
lib/fluent/plugin/buffer.rb:                  if u.unstaged? && !chunk_size_full?(u)
lib/fluent/plugin/buffer.rb:              elsif c.unstaged?
lib/fluent/plugin/buffer.rb:                enqueue_unstaged_chunk(c)
lib/fluent/plugin/buffer.rb:            if chunk.unstaged?
lib/fluent/plugin/buffer.rb:              chunk.purge rescue nil # to prevent leakage of unstaged chunks
lib/fluent/plugin/buffer.rb:      def enqueue_unstaged_chunk(chunk)
lib/fluent/plugin/buffer.rb:        log.on_trace { log.trace "enqueueing unstaged chunk", instance: self.object_id, metadata: chunk.metadata }
lib/fluent/plugin/buffer.rb:      # 3. create unstaged chunk and append rest splits -> repeat it for all splits
lib/fluent/plugin/buffer.rb:              chunk.purge if chunk.unstaged? # unstaged chunk will leak unless purge it
lib/fluent/plugin/buffer.rb:          if mc.unstaged?
lib/fluent/plugin/buffer/chunk.rb:          # state: unstaged/staged/queued/closed
lib/fluent/plugin/buffer/chunk.rb:          @state = :unstaged
lib/fluent/plugin/buffer/chunk.rb:          @state == :staged || @state == :unstaged
lib/fluent/plugin/buffer/chunk.rb:        def unstaged?
lib/fluent/plugin/buffer/chunk.rb:          @state == :unstaged
lib/fluent/plugin/buffer/chunk.rb:        def unstaged!
lib/fluent/plugin/buffer/chunk.rb:          @state = :unstaged
lib/fluent/plugin/buffer/file_chunk.rb:          @state = :unstaged
lib/fluent/plugin/buffer/file_single_chunk.rb:          @state = :unstaged
```
