### ISSUE TITLE
can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by calj** [fabric8io/fluent-plugin-kubernetes_metadata_filter#237]
I'm getting the following error:

```
2020-06-16 21:19:06 +0000 [warn]: #0 emit transaction failed: error_class=RuntimeError error="can't add a new key into hash during iteration" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:32:in `merge!'" tag="kubernetes.var.log.containers.prod-nginx-ingress-controller-jh96x_prod-backend_nginx-ingress-controller-f7cc28daace3e15edef798f9a3ccba41a9bb51866cfdb0376783fbb65d38b856.log" 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:32:in `merge!' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:32:in `get_pod_metadata' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:309:in `get_metadata_for_record' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:358:in `block in filter_stream' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event.rb:196:in `block in each' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event.rb:195:in `each' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event.rb:195:in `each' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.4.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:342:in `filter_stream' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event_router.rb:178:in `block in filter_stream' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event_router.rb:178:in `each' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event_router.rb:178:in `reduce' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event_router.rb:178:in `filter_stream' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event_router.rb:159:in `emit_events' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/event_router.rb:97:in `emit_stream' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.9/lib/fluent/plugin/out_elasticsearch.rb:979:in `rescue in send_bulk' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.9/lib/fluent/plugin/out_elasticsearch.rb:957:in `send_bulk' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.9/lib/fluent/plugin/out_elasticsearch.rb:789:in `block in write' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.9/lib/fluent/plugin/out_elasticsearch.rb:788:in `each' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.9/lib/fluent/plugin/out_elasticsearch.rb:788:in `write' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1133:in `try_flush' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1439:in `flush_thread_run' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start' 
  2020-06-16 21:19:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.9.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create' 
2020-06-16 21:19:06 +0000 [warn]: #0 [out_es] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-06-16 21:19:07 +0000 chunk="5a83a177012727a729d4b57555e180b9" error_class=RuntimeError error="can't add a new key into hash during iteration" 
```

I reproduced this problem with versions 2.3.0 and 2.4.6

**Comment by jcantrill** [comment]
closing dup to #260
