### ISSUE TITLE
Alibabacloud kubernetes problem

### ISSUE THREAD

**Issue by bayucandra** [fabric8io/fluent-plugin-kubernetes_metadata_filter#260]
Hi,

Before I am working with Alibabacloud Kubernetes (ACK), I have deployed successfully to AWS EKS following configuration: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml

However, when moving to ACK, I got the following problem in the log which I am pretty sure it is caused by fluentd metadata plugin. Because when I am disabling it, fluentd works just fine. Here are the error logs which may be related to this plugin:

```
2020-09-12 02:40:06 +0000 [warn]: #0 emit transaction failed: error_class=RuntimeError error="can't add a new key into hash during iteration" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:32:in `merge!'" tag="kubernetes.var.log.containers.android-api-7c94dcd6cd-spmtp_emporia_jaeger-agent-d26a89d228506b18b8e855d33d81c72f441f4ebd64bb1de71968fa601823a065.log"
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:32:in `merge!'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:32:in `get_pod_metadata'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:295:in `get_metadata_for_record'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:344:in `block in filter_stream'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event.rb:196:in `block in each'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event.rb:195:in `each'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event.rb:195:in `each'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-kubernetes_metadata_filter-2.3.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:328:in `filter_stream'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `block in filter_stream'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `each'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `reduce'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event_router.rb:178:in `filter_stream'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event_router.rb:159:in `emit_events'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/event_router.rb:97:in `emit_stream'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:999:in `rescue in send_bulk'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:977:in `send_bulk'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:804:in `block in write'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:803:in `each'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.1.1/lib/fluent/plugin/out_elasticsearch.rb:803:in `write'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-09-12 02:40:06 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-09-12 02:40:07 +0000 [warn]: #0 [out_es] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-09-12 02:40:08 +0000 chunk="5af14b7b0835e9f3552264586d77c73b" error_class=RuntimeError error="can't add a new key into hash during iteration"
  2020-09-12 02:40:07 +0000 [warn]: #0 suppressed same stacktrace
2020-09-12 02:40:07 +0000 [warn]: #0 [out_es] retry succeeded. chunk_id="5af14b7d399bcadd667712c55bca4417"
```

Please note, it showing randomly with another container ( not only the container name showed above ). So, I don't think if it is related to a specific container problem.

**Comment by jcantrill** [comment]
@grosser you made some recent changes to the caching.  Any thoughts if this bug may no longer be present?

**Comment by grosser** [comment]
lots of changes ... some chance it is fixed, but doubt it

**Comment by jcantrill** [comment]
closing due to age. please re-open if issue persists
