### ISSUE TITLE
v0.22 or v0.23 causing nil->String conversions

### ISSUE THREAD

**Issue by therc** [fabric8io/fluent-plugin-kubernetes_metadata_filter#30]
Something broke between fabric8io/docker-fluentd-kubernetes v1.13 and v1.14 for me. The only changes are the Kubernetes metadata filter, which jumped from 0.21 to 0.22 and then 0.23.

These are the only two PRs merged in those releases:
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/1e82acf84a7b43e947f2745bf8d4a0327d1d2a46
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/beb0b85d0bb87bae936d1651b0ea95627da8daf5

While trying to figure the root cause, I noticed the stack traces:

```
2016-06-16 21:49:49 +0000 [warn]: [Fluent::ElasticsearchOutputDynamic] failed to flush the buffer. plugin_id="object:1a23180" retry_time=0 next_retry=2016-06-16 21:49:50 +0000 chunk="5356c373da2132319e73f720af223749" error_class=TypeError error="no implicit conversion of nil into String"
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:130:in `eval'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:130:in `block in write'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/event.rb:194:in `each'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/event.rb:194:in `block in each'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/buffer/memory_chunk.rb:90:in `open'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/buffer/memory_chunk.rb:90:in `open'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/event.rb:193:in `each'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:115:in `write'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/compat/output.rb:118:in `write'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/output.rb:778:in `try_flush'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/output.rb:953:in `flush_thread_run'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/output.rb:360:in `block (2 levels) in start'
  2016-06-16 21:49:49 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
```

Given that it's happening in elasticsearch_dynamic, perhaps nobody has noticed it yet because they don't use a setup like mine:

```
  <match **>
    type elasticsearch_dynamic
[...]
    logstash_format true
    logstash_prefix "logstash-jenkins-${record[\'kubernetes\'][\'namespace_name\']}"
[...]
```

Could it be that there are log entries now where `record['kubernetes']['namespace_name']` is not defined? That makes me suspect the systemd change. I'll try to debug some more, but my Ruby is non-existent.

cc @richm

**Comment by richm** [comment]
@therc was it working with fluentd 0.14 previously?

**Comment by richm** [comment]
Can you add a::

    <filter **>
      @type stdout
    </filter>

to see what the problematic record is?

**Comment by therc** [comment]
This setup works (v1.13 of the fluentd-kubernetes image):

```
2016-06-16 22:13:57 +0000 [info]: gem 'fluent-plugin-docker_metadata_filter' version '0.1.2'
2016-06-16 22:13:57 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.5.0'
2016-06-16 22:13:57 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.21.0'
2016-06-16 22:13:57 +0000 [info]: gem 'fluentd' version '0.14.0.pre.1'
2016-06-16 22:13:57 +0000 [info]: gem 'fluentd' version '0.12.23'
```

**Comment by therc** [comment]
On my toy cluster's master, where there's only fluentd running at the moment, I can only see this in the `docker logs` output:

```
[...]
  <filter **>
    @type stdout
  </filter>
</ROOT>
2016-06-16 22:53:30 +0000 [info]: following tail of /var/log/containers/fluentd-logging-4qdj6_kube-system_POD-00e26d4e58866b7e0c65a5d5aa11d00b67f859160348fb0e2a4c9b634e88652b.log
2016-06-16 22:53:30 +0000 [info]: following tail of /var/log/containers/fluentd-logging-ihff7_kube-system_POD-a142139dbcbdc55818b5d22960eef2654dc5450db64d6156aed5e60f533f3677.log
2016-06-16 22:53:30 +0000 [info]: following tail of /var/log/containers/fluentd-logging-ihff7_kube-system_fluentd-elasticsearch-e66881d9b4466940b930920ef1035767c6a3eecdf0cdd83c1973d1231dc6fc4b.log
2016-06-16 22:53:30 +0000 [info]: following tail of /var/log/containers/fluentd-logging-4qdj6_kube-system_fluentd-elasticsearch-51a83864c9f964583085fbab38766c4c79cdbfa9ec88682702e3e6f7d4889c77.log
2016-06-16 22:53:36 +0000 [warn]: [Fluent::ElasticsearchOutputDynamic] failed to flush the buffer. plugin_id="object:1e968e8" retry_time=0 next_retry=2016-06-16 22:53:37 +0000 chunk="5356d1b60fe236a9ef9f129b40373820" error_class=TypeError error="no implicit conversion of nil into String"
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:130:in `eval'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:130:in `block in write'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/event.rb:194:in `each'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/event.rb:194:in `block in each'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/buffer/memory_chunk.rb:90:in `open'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/buffer/memory_chunk.rb:90:in `open'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/event.rb:193:in `each'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:115:in `write'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/compat/output.rb:118:in `write'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/output.rb:778:in `try_flush'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/output.rb:953:in `flush_thread_run'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin/output.rb:360:in `block (2 levels) in start'
  2016-06-16 22:53:36 +0000 [warn]: /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/fluentd-0.14.0/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
```

**Comment by therc** [comment]
I put that filter at the end of the file, does it need to go somewhere else?

**Comment by richm** [comment]
yes, the filter needs to go before the `<match **>` - once fluentd hits that match, it will do no more processing.
If that proves to be too verbose, we can try and put a `begin/rescue` block in your dynamic index name evaluation (if elasticsearch_dynamic allows arbitrary ruby code in `${...}` blocks.

I don't understand - I didn't think I changed anything for the non-journal case . . .

**Comment by therc** [comment]
Ordering matters. If I put the filter at the top, it works, but it generates a nice amplification attack as fluentd-logging's entries get logged recursively. Still not clear what the problem is, though.

**Comment by richm** [comment]
Was everything working correctly with this commit?  https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/e2bcdb6a125d446efff7b1d98c8c08feeae82ff7

Can you paste some of the amplified recursive log output?  There might be a clue in there.

**Comment by richm** [comment]
re: match `type @stdout` - I don't know of a way to negate a match i.e. it would be nice to say `<match !**fluentd**> output to stdout`.

The next thing to try is add a `begin/rescue/end` block in your dynamic template i.e. something like this::

    logstash_prefix "logstash-jenkins-${begin record[\'kubernetes\'][\'namespace_name\'] rescue puts "Error reading time }[#{time}] tag [#{tag_parts}] record #{record}" end}"

I have not been able to reproduce the problem.

**Comment by richm** [comment]
@therc ping - any update?

**Comment by therc** [comment]
Sorry, I was swamped with other stuff. I think I found the culprit... fluent-plugin-elasticsearch doesn't support fluentd 0.14 anymore: 

https://github.com/uken/fluent-plugin-elasticsearch/commit/e10a3fb7454d227bc96914e9d9ea1e4b4945cb70

And the reasoning includes the error I mentioned:

https://github.com/uken/fluent-plugin-elasticsearch/issues/176

"TypeError: no implicit conversion of nil into String in eval on out_elasticsearch_dynamic.rb:130"

**Comment by richm** [comment]
@therc can we close this issue?
