### ISSUE TITLE
Failed to parse kubernetes.labels

### ISSUE THREAD

**Issue by tsn77130** [fabric8io/fluent-plugin-kubernetes_metadata_filter#32]
Hi,

I have following error when trying to use plugin, seems that labels are not parsed  :

My config : 
2016-07-15 10:13:23 +0000 [info]: reading config file path="/etc/fluent/fluent.conf"
2016-07-15 10:13:23 +0000 [info]: starting fluentd-0.14.1
2016-07-15 10:13:23 +0000 [info]: spawn command to main: /usr/bin/ruby2.3 -Eascii-8bit:ascii-8bit /usr/local/bin/fluentd --under-supervisor
2016-07-15 10:13:25 +0000 [info]: reading config file path="/etc/fluent/fluent.conf"
2016-07-15 10:13:25 +0000 [info]: starting fluentd-0.14.1 without supervision
2016-07-15 10:13:25 +0000 [info]: gem 'fluent-plugin-docker_metadata_filter' version '0.1.3'
2016-07-15 10:13:25 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.5.0'
2016-07-15 10:13:25 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.23.0'
2016-07-15 10:13:25 +0000 [info]: gem 'fluentd' version '0.14.1'
2016-07-15 10:13:25 +0000 [warn]: 'type' is deprecated parameter name. use '@type' instead.
2016-07-15 10:13:25 +0000 [info]: adding filter pattern="kubernetes.var.lib.docker.containers.*.*.log" type="kubernetes_metadata"
2016-07-15 10:13:40 +0000 [info]: adding match pattern="**" type="elasticsearch"

```

[2016-07-15 09:11:38,359][DEBUG][action.bulk              ] [Meathook] [logstash-2016.07.14][0] failed to execute bulk item (index) index 
{
[logstash-2016.07.14][fluentd][AVXt01G8bCJdaa2_HQWW]
, source[{"log":"2016-07-14 13:00:23+0200 [-] \n"
,"stream":"stdout"
,"time":"2016-07-14T11:00:23.333149774Z"
,"docker":
	{
	"container_id":"10d226075434af463109e997da757b6371073b4d04cd5928878febb8e3add246"
	}
,"kubernetes":
	{
	"namespace_name":"default"
	,"pod_id":"e388e50d-483b-11e6-a583-fa163e2ca80d"
	,"pod_name":"app_utev2-4228063734-q256u"
	,"container_name":"app_utev2"
	,"labels":
		{
		"app":"app_utev2"
		,"pod-template-hash":"4228063734"
		,"track":"stable"
		}
	,"host":"1xx.xxx.xxx.xxx"
	}
,"tag":"kubernetes.var.log.containers.app_utev2-4228063734-q256u_default_app_utev2-10d226075434af463109e997da757b6371073b4d04cd5928878febb8e3add246.log"
,"@timestamp":"2016-07-14T11:00:23.333149774Z"}]}





org.elasticsearch.index.mapper.MapperParsingException: failed to parse [kubernetes.labels]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:409)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:453)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [app]
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:331)
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:399)
        ... 14 more
```

**Comment by tsn77130** [comment]
Problem with json template, I close the issue.

**Comment by stibi** [comment]
Hello, can I ask how you fixed the problem? I'm having exactly the same problem right now…
It's something related to Elastic mapping JSON template? What have you modified?

**Comment by tsn77130** [comment]
Take a look at https://github.com/fabric8io/docker-fluentd-kubernetes/issues/9
If I remember correctly, I change my ES template.json 
In fact, I changed ES image, and used kubernetes/examples/elasticsearch/production_cluster in which template.json was OK)
