### ISSUE TITLE
Connection Reset By Peer

### ISSUE THREAD

**Issue by glend17** [fabric8io/fluent-plugin-kubernetes_metadata_filter#380]
I am using a daemonset and every time one pod is running healthy while the other one keeps going into restarts every 5 minutes

```#<Thread:0x00007f987b736110@/usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-0.27.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:200 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `sysread': Connection reset by peer (Errno::ECONNRESET)
	from /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `readpartial'
	from /usr/local/bundle/gems/http-0.9.8/lib/http/timeout/null.rb:41:in `readpartial'
	from /usr/local/bundle/gems/http-0.9.8/lib/http/connection.rb:210:in `read_more'
	from /usr/local/bundle/gems/http-0.9.8/lib/http/connection.rb:80:in `readpartial'
	from /usr/local/bundle/gems/http-0.9.8/lib/http/response/body.rb:21:in `readpartial'
	from /usr/local/bundle/gems/http-0.9.8/lib/http/response/body.rb:26:in `each'
	from /usr/local/bundle/gems/kubeclient-1.1.4/lib/kubeclient/watch_stream.rb:24:in `each'
	from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-0.27.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:386:in `start_watch'
	from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-0.27.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:200:in `block in configure'
Unexpected error Connection reset by peer
  /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `sysread'
  /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `readpartial'
  /usr/local/bundle/gems/http-0.9.8/lib/http/timeout/null.rb:41:in `readpartial'
  /usr/local/bundle/gems/http-0.9.8/lib/http/connection.rb:210:in `read_more'
  /usr/local/bundle/gems/http-0.9.8/lib/http/connection.rb:80:in `readpartial'
  /usr/local/bundle/gems/http-0.9.8/lib/http/response/body.rb:21:in `readpartial'
  /usr/local/bundle/gems/http-0.9.8/lib/http/response/body.rb:26:in `each'
  /usr/local/bundle/gems/kubeclient-1.1.4/lib/kubeclient/watch_stream.rb:24:in `each'
  /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-0.27.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:386:in `start_watch'
  /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-0.27.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:200:in `block in configure' 
  ```
  
  It fixes itself some times when doing rollout restart

**Comment by jcantrill** [comment]
`Unexpected error Connection reset by peer`

This typically is an issue unrelated to the library but something happening with the server.  There is nothing in this exception trace that would provide enough information to provide additional diagnostics.
