### ISSUE TITLE
Td-agent start failed.

### ISSUE THREAD

**Issue by gyj0825** [fabric8io/fluent-plugin-kubernetes_metadata_filter#50]
Add kubernetes_metadata cause td-agent start failed.
When start td-agent , throw error  "HTTP status code 400, Bad Request", what causes the error?

**version info:**
os  rhel7.2
td-agent version  2.3.3
fluent-plugin-kubernetes_metadata_filter (0.24.0)
ruby version  ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

**td-agent Configuration：**
<filter kubernetes.**>
  type kubernetes_metadata
  kubernetes_url https://10.253.1.240:8443
  verify_ssl false
  bearer_token_file /tmp/token
</filter>

**error log:**
2016-12-11 10:54:33 +0800 [info]: adding source type="kafka"
2016-12-11 10:54:33 +0800 [error]: unexpected error error="HTTP status code 400, Bad Request"
  2016-12-11 10:54:33 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/kubeclient-1.2.0/lib/kubeclient/watch_stream.rb:20:in `each'
  2016-12-11 10:54:33 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kubernetes_metadata_filter-0.24.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:362:in `start_watch'
  2016-12-11 10:54:33 +0800 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kubernetes_metadata_filter-0.24.0/lib/fluent/plugin/filter_kubernetes_metadata.rb:173:in `block in configure'
2016-12-11 10:54:33 +0800 [info]: process finished code=256
2016-12-11 10:54:33 +0800 [warn]: process died within 1 second. exit.

**Comment by ersushantsood** [comment]
I am also getting the same error . Is this issue being looked into?

**Comment by ersushantsood** [comment]
I am using below version and configs :  

version info:
os rhel7.2
td-agent version 2.3.5
fluent-plugin-kubernetes_metadata_filter (0.26.3)
ruby version ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

td-agent Configuration：
<filter kubernetes.**>
type kubernetes_metadata
kubernetes_url https://KUBERNETES_ENDPOINT:8443
verify_ssl false
bearer_token_file /tmp/token

**Comment by mindfulmonk** [comment]
I'm also hitting the same issue. The debug output doesn't really show what is wrong.

```
2017-05-25 13:19:05 +0000 [info]: using configuration file: <ROOT>
  <filter kubernetes.**>
    type kubernetes_metadata
    kubernetes_url "https://192.168.99.100:8443"
    bearer_token_file "/etc/fluent/token"
    ca_file "/etc/fluent/ca.crt"
    verify_ssl false
    include_namespace_id true
    use_journal false
    preserve_json_log true
  </filter>
  <match **>
    @type stdout
  </match>
</ROOT>
2017-05-25 13:19:05 +0000 [error]: unexpected error error_class=KubeException error="HTTP status code 400, Bad Request"
  2017-05-25 13:19:05 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/kubeclient-1.1.4/lib/kubeclient/watch_stream.rb:20:in `each'
  2017-05-25 13:19:05 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-0.26.2/lib/fluent/plugin/filter_kubernetes_metadata.rb:365:in `start_watch'
  2017-05-25 13:19:05 +0000 [error]: /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-0.26.2/lib/fluent/plugin/filter_kubernetes_metadata.rb:173:in `block in configure'
2017-05-25 13:19:05 +0000 [error]: unexpected error error="HTTP status code 400, Bad Request"
  2017-05-25 13:19:05 +0000 [error]: suppressed same stacktrace
2017-05-25 13:19:05 +0000 [info]: Worker 0 finished unexpectedly with status 1

```
